env = Environment(
	CXXFLAGS=['-std=c++17', '-g', '-O0', '-Wall', '-Wno-sign-compare'],
	CPPPATH=['.'],
	CPPDEFINES=['GLM_FORCE_RADIANS', 'GLM_ENABLE_EXPERIMENTAL']
)

geom_objs = env.Object(['utility.cpp'])

env.Program(['test_expand.cpp'])
env.Program(['test_rotations.cpp', geom_objs])
env.Program(['test_print.cpp', geom_objs])
env.Program(['test_intersects.cpp', geom_objs])
